#pragma once

// tolua_begin
enum ENUM_ENTITY_EFFECT
{
	E_EFFECT_SPEED = 1,
	E_EFFECT_SLOWNESS = 2,
	E_EFFECT_HASTE = 3,
	E_EFFECT_MINING_FATIGUE = 4,
	E_EFFECT_STENGTH = 5,
	E_EFFECT_INSTANT_HEALTH = 6,
	E_EFFECT_INSTANT_DAMAGE = 7,
	E_EFFECT_JUMP_BOOST = 8,
	E_EFFECT_NAUSEA = 9,
	E_EFFECT_REGENERATION = 10,
	E_EFFECT_RESISTANCE = 11,
	E_EFFECT_FIRE_RESISTANCE = 12,
	E_EFFECT_WATER_BREATHING = 13,
	E_EFFECT_INVISIBILITY = 14,
	E_EFFECT_BLINDNESS = 15,
	E_EFFECT_NIGHT_VISION = 16,
	E_EFFECT_HUNGER = 17,
	E_EFFECT_WEAKNESS = 18,
	E_EFFECT_POISON = 19,
	E_EFFECT_WITHER = 20,
	E_EFFECT_HEALTH_BOOST = 21,
	E_EFFECT_ABSORPTION = 22,
	E_EFFECT_SATURATION = 23,
} ;