#!/bin/sh

# This script runs Cuberite under helgrind
# It expects valgrind to be normally installed and available
# Note that this is for Linux only and debug-only, since it slows down MCS way too much

exec valgrind --log-file=helgrind.log --suppressions=hg.supp --gen-suppressions=all --tool=helgrind -v ./Cuberite
