#!/bin/sh

# This script runs Cuberite under valgrind
# It expects valgrind to be normally installed and available
# Note that this is for Linux only and debug-only, since it slows down MCS way too much

exec valgrind --log-file=valgrind.log --suppressions=vg.supp --tool=memcheck --leak-check=full --leak-resolution=high --show-reachable=yes --track-origins=yes -v ./Cuberite
