# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tycho/MCServer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tycho/MCServer

# Include any dependencies generated for this target.
include src/CMakeFiles/../MCServer/MCServer.dir/depend.make

# Include the progress variables for this target.
include src/CMakeFiles/../MCServer/MCServer.dir/progress.make

# Include the compile flags for this target's objects.
include src/CMakeFiles/../MCServer/MCServer.dir/flags.make

src/CMakeFiles/../MCServer/MCServer.dir/main.cpp.o: src/CMakeFiles/../MCServer/MCServer.dir/flags.make
src/CMakeFiles/../MCServer/MCServer.dir/main.cpp.o: src/main.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/tycho/MCServer/CMakeFiles $(CMAKE_PROGRESS_1)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object src/CMakeFiles/../MCServer/MCServer.dir/main.cpp.o"
	cd /home/tycho/MCServer/src && /usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/../MCServer/MCServer.dir/main.cpp.o -c /home/tycho/MCServer/src/main.cpp

src/CMakeFiles/../MCServer/MCServer.dir/main.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../MCServer/MCServer.dir/main.cpp.i"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/tycho/MCServer/src/main.cpp > CMakeFiles/../MCServer/MCServer.dir/main.cpp.i

src/CMakeFiles/../MCServer/MCServer.dir/main.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../MCServer/MCServer.dir/main.cpp.s"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/tycho/MCServer/src/main.cpp -o CMakeFiles/../MCServer/MCServer.dir/main.cpp.s

src/CMakeFiles/../MCServer/MCServer.dir/main.cpp.o.requires:
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/main.cpp.o.requires

src/CMakeFiles/../MCServer/MCServer.dir/main.cpp.o.provides: src/CMakeFiles/../MCServer/MCServer.dir/main.cpp.o.requires
	$(MAKE) -f src/CMakeFiles/../MCServer/MCServer.dir/build.make src/CMakeFiles/../MCServer/MCServer.dir/main.cpp.o.provides.build
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/main.cpp.o.provides

src/CMakeFiles/../MCServer/MCServer.dir/main.cpp.o.provides.build: src/CMakeFiles/../MCServer/MCServer.dir/main.cpp.o

src/CMakeFiles/../MCServer/MCServer.dir/Root.cpp.o: src/CMakeFiles/../MCServer/MCServer.dir/flags.make
src/CMakeFiles/../MCServer/MCServer.dir/Root.cpp.o: src/Root.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/tycho/MCServer/CMakeFiles $(CMAKE_PROGRESS_2)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object src/CMakeFiles/../MCServer/MCServer.dir/Root.cpp.o"
	cd /home/tycho/MCServer/src && /usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/../MCServer/MCServer.dir/Root.cpp.o -c /home/tycho/MCServer/src/Root.cpp

src/CMakeFiles/../MCServer/MCServer.dir/Root.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../MCServer/MCServer.dir/Root.cpp.i"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/tycho/MCServer/src/Root.cpp > CMakeFiles/../MCServer/MCServer.dir/Root.cpp.i

src/CMakeFiles/../MCServer/MCServer.dir/Root.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../MCServer/MCServer.dir/Root.cpp.s"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/tycho/MCServer/src/Root.cpp -o CMakeFiles/../MCServer/MCServer.dir/Root.cpp.s

src/CMakeFiles/../MCServer/MCServer.dir/Root.cpp.o.requires:
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/Root.cpp.o.requires

src/CMakeFiles/../MCServer/MCServer.dir/Root.cpp.o.provides: src/CMakeFiles/../MCServer/MCServer.dir/Root.cpp.o.requires
	$(MAKE) -f src/CMakeFiles/../MCServer/MCServer.dir/build.make src/CMakeFiles/../MCServer/MCServer.dir/Root.cpp.o.provides.build
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/Root.cpp.o.provides

src/CMakeFiles/../MCServer/MCServer.dir/Root.cpp.o.provides.build: src/CMakeFiles/../MCServer/MCServer.dir/Root.cpp.o

src/CMakeFiles/../MCServer/MCServer.dir/MCLogger.cpp.o: src/CMakeFiles/../MCServer/MCServer.dir/flags.make
src/CMakeFiles/../MCServer/MCServer.dir/MCLogger.cpp.o: src/MCLogger.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/tycho/MCServer/CMakeFiles $(CMAKE_PROGRESS_3)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object src/CMakeFiles/../MCServer/MCServer.dir/MCLogger.cpp.o"
	cd /home/tycho/MCServer/src && /usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/../MCServer/MCServer.dir/MCLogger.cpp.o -c /home/tycho/MCServer/src/MCLogger.cpp

src/CMakeFiles/../MCServer/MCServer.dir/MCLogger.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../MCServer/MCServer.dir/MCLogger.cpp.i"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/tycho/MCServer/src/MCLogger.cpp > CMakeFiles/../MCServer/MCServer.dir/MCLogger.cpp.i

src/CMakeFiles/../MCServer/MCServer.dir/MCLogger.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../MCServer/MCServer.dir/MCLogger.cpp.s"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/tycho/MCServer/src/MCLogger.cpp -o CMakeFiles/../MCServer/MCServer.dir/MCLogger.cpp.s

src/CMakeFiles/../MCServer/MCServer.dir/MCLogger.cpp.o.requires:
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/MCLogger.cpp.o.requires

src/CMakeFiles/../MCServer/MCServer.dir/MCLogger.cpp.o.provides: src/CMakeFiles/../MCServer/MCServer.dir/MCLogger.cpp.o.requires
	$(MAKE) -f src/CMakeFiles/../MCServer/MCServer.dir/build.make src/CMakeFiles/../MCServer/MCServer.dir/MCLogger.cpp.o.provides.build
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/MCLogger.cpp.o.provides

src/CMakeFiles/../MCServer/MCServer.dir/MCLogger.cpp.o.provides.build: src/CMakeFiles/../MCServer/MCServer.dir/MCLogger.cpp.o

src/CMakeFiles/../MCServer/MCServer.dir/Authenticator.cpp.o: src/CMakeFiles/../MCServer/MCServer.dir/flags.make
src/CMakeFiles/../MCServer/MCServer.dir/Authenticator.cpp.o: src/Authenticator.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/tycho/MCServer/CMakeFiles $(CMAKE_PROGRESS_4)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object src/CMakeFiles/../MCServer/MCServer.dir/Authenticator.cpp.o"
	cd /home/tycho/MCServer/src && /usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/../MCServer/MCServer.dir/Authenticator.cpp.o -c /home/tycho/MCServer/src/Authenticator.cpp

src/CMakeFiles/../MCServer/MCServer.dir/Authenticator.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../MCServer/MCServer.dir/Authenticator.cpp.i"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/tycho/MCServer/src/Authenticator.cpp > CMakeFiles/../MCServer/MCServer.dir/Authenticator.cpp.i

src/CMakeFiles/../MCServer/MCServer.dir/Authenticator.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../MCServer/MCServer.dir/Authenticator.cpp.s"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/tycho/MCServer/src/Authenticator.cpp -o CMakeFiles/../MCServer/MCServer.dir/Authenticator.cpp.s

src/CMakeFiles/../MCServer/MCServer.dir/Authenticator.cpp.o.requires:
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/Authenticator.cpp.o.requires

src/CMakeFiles/../MCServer/MCServer.dir/Authenticator.cpp.o.provides: src/CMakeFiles/../MCServer/MCServer.dir/Authenticator.cpp.o.requires
	$(MAKE) -f src/CMakeFiles/../MCServer/MCServer.dir/build.make src/CMakeFiles/../MCServer/MCServer.dir/Authenticator.cpp.o.provides.build
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/Authenticator.cpp.o.provides

src/CMakeFiles/../MCServer/MCServer.dir/Authenticator.cpp.o.provides.build: src/CMakeFiles/../MCServer/MCServer.dir/Authenticator.cpp.o

src/CMakeFiles/../MCServer/MCServer.dir/StringUtils.cpp.o: src/CMakeFiles/../MCServer/MCServer.dir/flags.make
src/CMakeFiles/../MCServer/MCServer.dir/StringUtils.cpp.o: src/StringUtils.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/tycho/MCServer/CMakeFiles $(CMAKE_PROGRESS_5)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object src/CMakeFiles/../MCServer/MCServer.dir/StringUtils.cpp.o"
	cd /home/tycho/MCServer/src && /usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/../MCServer/MCServer.dir/StringUtils.cpp.o -c /home/tycho/MCServer/src/StringUtils.cpp

src/CMakeFiles/../MCServer/MCServer.dir/StringUtils.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../MCServer/MCServer.dir/StringUtils.cpp.i"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/tycho/MCServer/src/StringUtils.cpp > CMakeFiles/../MCServer/MCServer.dir/StringUtils.cpp.i

src/CMakeFiles/../MCServer/MCServer.dir/StringUtils.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../MCServer/MCServer.dir/StringUtils.cpp.s"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/tycho/MCServer/src/StringUtils.cpp -o CMakeFiles/../MCServer/MCServer.dir/StringUtils.cpp.s

src/CMakeFiles/../MCServer/MCServer.dir/StringUtils.cpp.o.requires:
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/StringUtils.cpp.o.requires

src/CMakeFiles/../MCServer/MCServer.dir/StringUtils.cpp.o.provides: src/CMakeFiles/../MCServer/MCServer.dir/StringUtils.cpp.o.requires
	$(MAKE) -f src/CMakeFiles/../MCServer/MCServer.dir/build.make src/CMakeFiles/../MCServer/MCServer.dir/StringUtils.cpp.o.provides.build
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/StringUtils.cpp.o.provides

src/CMakeFiles/../MCServer/MCServer.dir/StringUtils.cpp.o.provides.build: src/CMakeFiles/../MCServer/MCServer.dir/StringUtils.cpp.o

src/CMakeFiles/../MCServer/MCServer.dir/Server.cpp.o: src/CMakeFiles/../MCServer/MCServer.dir/flags.make
src/CMakeFiles/../MCServer/MCServer.dir/Server.cpp.o: src/Server.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/tycho/MCServer/CMakeFiles $(CMAKE_PROGRESS_6)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object src/CMakeFiles/../MCServer/MCServer.dir/Server.cpp.o"
	cd /home/tycho/MCServer/src && /usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/../MCServer/MCServer.dir/Server.cpp.o -c /home/tycho/MCServer/src/Server.cpp

src/CMakeFiles/../MCServer/MCServer.dir/Server.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../MCServer/MCServer.dir/Server.cpp.i"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/tycho/MCServer/src/Server.cpp > CMakeFiles/../MCServer/MCServer.dir/Server.cpp.i

src/CMakeFiles/../MCServer/MCServer.dir/Server.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../MCServer/MCServer.dir/Server.cpp.s"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/tycho/MCServer/src/Server.cpp -o CMakeFiles/../MCServer/MCServer.dir/Server.cpp.s

src/CMakeFiles/../MCServer/MCServer.dir/Server.cpp.o.requires:
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/Server.cpp.o.requires

src/CMakeFiles/../MCServer/MCServer.dir/Server.cpp.o.provides: src/CMakeFiles/../MCServer/MCServer.dir/Server.cpp.o.requires
	$(MAKE) -f src/CMakeFiles/../MCServer/MCServer.dir/build.make src/CMakeFiles/../MCServer/MCServer.dir/Server.cpp.o.provides.build
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/Server.cpp.o.provides

src/CMakeFiles/../MCServer/MCServer.dir/Server.cpp.o.provides.build: src/CMakeFiles/../MCServer/MCServer.dir/Server.cpp.o

src/CMakeFiles/../MCServer/MCServer.dir/DeadlockDetect.cpp.o: src/CMakeFiles/../MCServer/MCServer.dir/flags.make
src/CMakeFiles/../MCServer/MCServer.dir/DeadlockDetect.cpp.o: src/DeadlockDetect.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/tycho/MCServer/CMakeFiles $(CMAKE_PROGRESS_7)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object src/CMakeFiles/../MCServer/MCServer.dir/DeadlockDetect.cpp.o"
	cd /home/tycho/MCServer/src && /usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/../MCServer/MCServer.dir/DeadlockDetect.cpp.o -c /home/tycho/MCServer/src/DeadlockDetect.cpp

src/CMakeFiles/../MCServer/MCServer.dir/DeadlockDetect.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../MCServer/MCServer.dir/DeadlockDetect.cpp.i"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/tycho/MCServer/src/DeadlockDetect.cpp > CMakeFiles/../MCServer/MCServer.dir/DeadlockDetect.cpp.i

src/CMakeFiles/../MCServer/MCServer.dir/DeadlockDetect.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../MCServer/MCServer.dir/DeadlockDetect.cpp.s"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/tycho/MCServer/src/DeadlockDetect.cpp -o CMakeFiles/../MCServer/MCServer.dir/DeadlockDetect.cpp.s

src/CMakeFiles/../MCServer/MCServer.dir/DeadlockDetect.cpp.o.requires:
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/DeadlockDetect.cpp.o.requires

src/CMakeFiles/../MCServer/MCServer.dir/DeadlockDetect.cpp.o.provides: src/CMakeFiles/../MCServer/MCServer.dir/DeadlockDetect.cpp.o.requires
	$(MAKE) -f src/CMakeFiles/../MCServer/MCServer.dir/build.make src/CMakeFiles/../MCServer/MCServer.dir/DeadlockDetect.cpp.o.provides.build
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/DeadlockDetect.cpp.o.provides

src/CMakeFiles/../MCServer/MCServer.dir/DeadlockDetect.cpp.o.provides.build: src/CMakeFiles/../MCServer/MCServer.dir/DeadlockDetect.cpp.o

src/CMakeFiles/../MCServer/MCServer.dir/WebAdmin.cpp.o: src/CMakeFiles/../MCServer/MCServer.dir/flags.make
src/CMakeFiles/../MCServer/MCServer.dir/WebAdmin.cpp.o: src/WebAdmin.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/tycho/MCServer/CMakeFiles $(CMAKE_PROGRESS_8)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object src/CMakeFiles/../MCServer/MCServer.dir/WebAdmin.cpp.o"
	cd /home/tycho/MCServer/src && /usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/../MCServer/MCServer.dir/WebAdmin.cpp.o -c /home/tycho/MCServer/src/WebAdmin.cpp

src/CMakeFiles/../MCServer/MCServer.dir/WebAdmin.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../MCServer/MCServer.dir/WebAdmin.cpp.i"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/tycho/MCServer/src/WebAdmin.cpp > CMakeFiles/../MCServer/MCServer.dir/WebAdmin.cpp.i

src/CMakeFiles/../MCServer/MCServer.dir/WebAdmin.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../MCServer/MCServer.dir/WebAdmin.cpp.s"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/tycho/MCServer/src/WebAdmin.cpp -o CMakeFiles/../MCServer/MCServer.dir/WebAdmin.cpp.s

src/CMakeFiles/../MCServer/MCServer.dir/WebAdmin.cpp.o.requires:
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/WebAdmin.cpp.o.requires

src/CMakeFiles/../MCServer/MCServer.dir/WebAdmin.cpp.o.provides: src/CMakeFiles/../MCServer/MCServer.dir/WebAdmin.cpp.o.requires
	$(MAKE) -f src/CMakeFiles/../MCServer/MCServer.dir/build.make src/CMakeFiles/../MCServer/MCServer.dir/WebAdmin.cpp.o.provides.build
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/WebAdmin.cpp.o.provides

src/CMakeFiles/../MCServer/MCServer.dir/WebAdmin.cpp.o.provides.build: src/CMakeFiles/../MCServer/MCServer.dir/WebAdmin.cpp.o

src/CMakeFiles/../MCServer/MCServer.dir/GroupManager.cpp.o: src/CMakeFiles/../MCServer/MCServer.dir/flags.make
src/CMakeFiles/../MCServer/MCServer.dir/GroupManager.cpp.o: src/GroupManager.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/tycho/MCServer/CMakeFiles $(CMAKE_PROGRESS_9)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object src/CMakeFiles/../MCServer/MCServer.dir/GroupManager.cpp.o"
	cd /home/tycho/MCServer/src && /usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/../MCServer/MCServer.dir/GroupManager.cpp.o -c /home/tycho/MCServer/src/GroupManager.cpp

src/CMakeFiles/../MCServer/MCServer.dir/GroupManager.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../MCServer/MCServer.dir/GroupManager.cpp.i"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/tycho/MCServer/src/GroupManager.cpp > CMakeFiles/../MCServer/MCServer.dir/GroupManager.cpp.i

src/CMakeFiles/../MCServer/MCServer.dir/GroupManager.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../MCServer/MCServer.dir/GroupManager.cpp.s"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/tycho/MCServer/src/GroupManager.cpp -o CMakeFiles/../MCServer/MCServer.dir/GroupManager.cpp.s

src/CMakeFiles/../MCServer/MCServer.dir/GroupManager.cpp.o.requires:
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/GroupManager.cpp.o.requires

src/CMakeFiles/../MCServer/MCServer.dir/GroupManager.cpp.o.provides: src/CMakeFiles/../MCServer/MCServer.dir/GroupManager.cpp.o.requires
	$(MAKE) -f src/CMakeFiles/../MCServer/MCServer.dir/build.make src/CMakeFiles/../MCServer/MCServer.dir/GroupManager.cpp.o.provides.build
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/GroupManager.cpp.o.provides

src/CMakeFiles/../MCServer/MCServer.dir/GroupManager.cpp.o.provides.build: src/CMakeFiles/../MCServer/MCServer.dir/GroupManager.cpp.o

src/CMakeFiles/../MCServer/MCServer.dir/CraftingRecipes.cpp.o: src/CMakeFiles/../MCServer/MCServer.dir/flags.make
src/CMakeFiles/../MCServer/MCServer.dir/CraftingRecipes.cpp.o: src/CraftingRecipes.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/tycho/MCServer/CMakeFiles $(CMAKE_PROGRESS_10)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object src/CMakeFiles/../MCServer/MCServer.dir/CraftingRecipes.cpp.o"
	cd /home/tycho/MCServer/src && /usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/../MCServer/MCServer.dir/CraftingRecipes.cpp.o -c /home/tycho/MCServer/src/CraftingRecipes.cpp

src/CMakeFiles/../MCServer/MCServer.dir/CraftingRecipes.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../MCServer/MCServer.dir/CraftingRecipes.cpp.i"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/tycho/MCServer/src/CraftingRecipes.cpp > CMakeFiles/../MCServer/MCServer.dir/CraftingRecipes.cpp.i

src/CMakeFiles/../MCServer/MCServer.dir/CraftingRecipes.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../MCServer/MCServer.dir/CraftingRecipes.cpp.s"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/tycho/MCServer/src/CraftingRecipes.cpp -o CMakeFiles/../MCServer/MCServer.dir/CraftingRecipes.cpp.s

src/CMakeFiles/../MCServer/MCServer.dir/CraftingRecipes.cpp.o.requires:
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/CraftingRecipes.cpp.o.requires

src/CMakeFiles/../MCServer/MCServer.dir/CraftingRecipes.cpp.o.provides: src/CMakeFiles/../MCServer/MCServer.dir/CraftingRecipes.cpp.o.requires
	$(MAKE) -f src/CMakeFiles/../MCServer/MCServer.dir/build.make src/CMakeFiles/../MCServer/MCServer.dir/CraftingRecipes.cpp.o.provides.build
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/CraftingRecipes.cpp.o.provides

src/CMakeFiles/../MCServer/MCServer.dir/CraftingRecipes.cpp.o.provides.build: src/CMakeFiles/../MCServer/MCServer.dir/CraftingRecipes.cpp.o

src/CMakeFiles/../MCServer/MCServer.dir/FurnaceRecipe.cpp.o: src/CMakeFiles/../MCServer/MCServer.dir/flags.make
src/CMakeFiles/../MCServer/MCServer.dir/FurnaceRecipe.cpp.o: src/FurnaceRecipe.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/tycho/MCServer/CMakeFiles $(CMAKE_PROGRESS_11)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object src/CMakeFiles/../MCServer/MCServer.dir/FurnaceRecipe.cpp.o"
	cd /home/tycho/MCServer/src && /usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/../MCServer/MCServer.dir/FurnaceRecipe.cpp.o -c /home/tycho/MCServer/src/FurnaceRecipe.cpp

src/CMakeFiles/../MCServer/MCServer.dir/FurnaceRecipe.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../MCServer/MCServer.dir/FurnaceRecipe.cpp.i"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/tycho/MCServer/src/FurnaceRecipe.cpp > CMakeFiles/../MCServer/MCServer.dir/FurnaceRecipe.cpp.i

src/CMakeFiles/../MCServer/MCServer.dir/FurnaceRecipe.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../MCServer/MCServer.dir/FurnaceRecipe.cpp.s"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/tycho/MCServer/src/FurnaceRecipe.cpp -o CMakeFiles/../MCServer/MCServer.dir/FurnaceRecipe.cpp.s

src/CMakeFiles/../MCServer/MCServer.dir/FurnaceRecipe.cpp.o.requires:
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/FurnaceRecipe.cpp.o.requires

src/CMakeFiles/../MCServer/MCServer.dir/FurnaceRecipe.cpp.o.provides: src/CMakeFiles/../MCServer/MCServer.dir/FurnaceRecipe.cpp.o.requires
	$(MAKE) -f src/CMakeFiles/../MCServer/MCServer.dir/build.make src/CMakeFiles/../MCServer/MCServer.dir/FurnaceRecipe.cpp.o.provides.build
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/FurnaceRecipe.cpp.o.provides

src/CMakeFiles/../MCServer/MCServer.dir/FurnaceRecipe.cpp.o.provides.build: src/CMakeFiles/../MCServer/MCServer.dir/FurnaceRecipe.cpp.o

src/CMakeFiles/../MCServer/MCServer.dir/MonsterConfig.cpp.o: src/CMakeFiles/../MCServer/MCServer.dir/flags.make
src/CMakeFiles/../MCServer/MCServer.dir/MonsterConfig.cpp.o: src/MonsterConfig.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/tycho/MCServer/CMakeFiles $(CMAKE_PROGRESS_12)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object src/CMakeFiles/../MCServer/MCServer.dir/MonsterConfig.cpp.o"
	cd /home/tycho/MCServer/src && /usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/../MCServer/MCServer.dir/MonsterConfig.cpp.o -c /home/tycho/MCServer/src/MonsterConfig.cpp

src/CMakeFiles/../MCServer/MCServer.dir/MonsterConfig.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../MCServer/MCServer.dir/MonsterConfig.cpp.i"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/tycho/MCServer/src/MonsterConfig.cpp > CMakeFiles/../MCServer/MCServer.dir/MonsterConfig.cpp.i

src/CMakeFiles/../MCServer/MCServer.dir/MonsterConfig.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../MCServer/MCServer.dir/MonsterConfig.cpp.s"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/tycho/MCServer/src/MonsterConfig.cpp -o CMakeFiles/../MCServer/MCServer.dir/MonsterConfig.cpp.s

src/CMakeFiles/../MCServer/MCServer.dir/MonsterConfig.cpp.o.requires:
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/MonsterConfig.cpp.o.requires

src/CMakeFiles/../MCServer/MCServer.dir/MonsterConfig.cpp.o.provides: src/CMakeFiles/../MCServer/MCServer.dir/MonsterConfig.cpp.o.requires
	$(MAKE) -f src/CMakeFiles/../MCServer/MCServer.dir/build.make src/CMakeFiles/../MCServer/MCServer.dir/MonsterConfig.cpp.o.provides.build
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/MonsterConfig.cpp.o.provides

src/CMakeFiles/../MCServer/MCServer.dir/MonsterConfig.cpp.o.provides.build: src/CMakeFiles/../MCServer/MCServer.dir/MonsterConfig.cpp.o

src/CMakeFiles/../MCServer/MCServer.dir/World.cpp.o: src/CMakeFiles/../MCServer/MCServer.dir/flags.make
src/CMakeFiles/../MCServer/MCServer.dir/World.cpp.o: src/World.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/tycho/MCServer/CMakeFiles $(CMAKE_PROGRESS_13)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object src/CMakeFiles/../MCServer/MCServer.dir/World.cpp.o"
	cd /home/tycho/MCServer/src && /usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/../MCServer/MCServer.dir/World.cpp.o -c /home/tycho/MCServer/src/World.cpp

src/CMakeFiles/../MCServer/MCServer.dir/World.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../MCServer/MCServer.dir/World.cpp.i"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/tycho/MCServer/src/World.cpp > CMakeFiles/../MCServer/MCServer.dir/World.cpp.i

src/CMakeFiles/../MCServer/MCServer.dir/World.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../MCServer/MCServer.dir/World.cpp.s"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/tycho/MCServer/src/World.cpp -o CMakeFiles/../MCServer/MCServer.dir/World.cpp.s

src/CMakeFiles/../MCServer/MCServer.dir/World.cpp.o.requires:
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/World.cpp.o.requires

src/CMakeFiles/../MCServer/MCServer.dir/World.cpp.o.provides: src/CMakeFiles/../MCServer/MCServer.dir/World.cpp.o.requires
	$(MAKE) -f src/CMakeFiles/../MCServer/MCServer.dir/build.make src/CMakeFiles/../MCServer/MCServer.dir/World.cpp.o.provides.build
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/World.cpp.o.provides

src/CMakeFiles/../MCServer/MCServer.dir/World.cpp.o.provides.build: src/CMakeFiles/../MCServer/MCServer.dir/World.cpp.o

src/CMakeFiles/../MCServer/MCServer.dir/CommandOutput.cpp.o: src/CMakeFiles/../MCServer/MCServer.dir/flags.make
src/CMakeFiles/../MCServer/MCServer.dir/CommandOutput.cpp.o: src/CommandOutput.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/tycho/MCServer/CMakeFiles $(CMAKE_PROGRESS_14)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object src/CMakeFiles/../MCServer/MCServer.dir/CommandOutput.cpp.o"
	cd /home/tycho/MCServer/src && /usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/../MCServer/MCServer.dir/CommandOutput.cpp.o -c /home/tycho/MCServer/src/CommandOutput.cpp

src/CMakeFiles/../MCServer/MCServer.dir/CommandOutput.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../MCServer/MCServer.dir/CommandOutput.cpp.i"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/tycho/MCServer/src/CommandOutput.cpp > CMakeFiles/../MCServer/MCServer.dir/CommandOutput.cpp.i

src/CMakeFiles/../MCServer/MCServer.dir/CommandOutput.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../MCServer/MCServer.dir/CommandOutput.cpp.s"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/tycho/MCServer/src/CommandOutput.cpp -o CMakeFiles/../MCServer/MCServer.dir/CommandOutput.cpp.s

src/CMakeFiles/../MCServer/MCServer.dir/CommandOutput.cpp.o.requires:
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/CommandOutput.cpp.o.requires

src/CMakeFiles/../MCServer/MCServer.dir/CommandOutput.cpp.o.provides: src/CMakeFiles/../MCServer/MCServer.dir/CommandOutput.cpp.o.requires
	$(MAKE) -f src/CMakeFiles/../MCServer/MCServer.dir/build.make src/CMakeFiles/../MCServer/MCServer.dir/CommandOutput.cpp.o.provides.build
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/CommandOutput.cpp.o.provides

src/CMakeFiles/../MCServer/MCServer.dir/CommandOutput.cpp.o.provides.build: src/CMakeFiles/../MCServer/MCServer.dir/CommandOutput.cpp.o

src/CMakeFiles/../MCServer/MCServer.dir/RCONServer.cpp.o: src/CMakeFiles/../MCServer/MCServer.dir/flags.make
src/CMakeFiles/../MCServer/MCServer.dir/RCONServer.cpp.o: src/RCONServer.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/tycho/MCServer/CMakeFiles $(CMAKE_PROGRESS_15)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object src/CMakeFiles/../MCServer/MCServer.dir/RCONServer.cpp.o"
	cd /home/tycho/MCServer/src && /usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/../MCServer/MCServer.dir/RCONServer.cpp.o -c /home/tycho/MCServer/src/RCONServer.cpp

src/CMakeFiles/../MCServer/MCServer.dir/RCONServer.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../MCServer/MCServer.dir/RCONServer.cpp.i"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/tycho/MCServer/src/RCONServer.cpp > CMakeFiles/../MCServer/MCServer.dir/RCONServer.cpp.i

src/CMakeFiles/../MCServer/MCServer.dir/RCONServer.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../MCServer/MCServer.dir/RCONServer.cpp.s"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/tycho/MCServer/src/RCONServer.cpp -o CMakeFiles/../MCServer/MCServer.dir/RCONServer.cpp.s

src/CMakeFiles/../MCServer/MCServer.dir/RCONServer.cpp.o.requires:
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/RCONServer.cpp.o.requires

src/CMakeFiles/../MCServer/MCServer.dir/RCONServer.cpp.o.provides: src/CMakeFiles/../MCServer/MCServer.dir/RCONServer.cpp.o.requires
	$(MAKE) -f src/CMakeFiles/../MCServer/MCServer.dir/build.make src/CMakeFiles/../MCServer/MCServer.dir/RCONServer.cpp.o.provides.build
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/RCONServer.cpp.o.provides

src/CMakeFiles/../MCServer/MCServer.dir/RCONServer.cpp.o.provides.build: src/CMakeFiles/../MCServer/MCServer.dir/RCONServer.cpp.o

src/CMakeFiles/../MCServer/MCServer.dir/Log.cpp.o: src/CMakeFiles/../MCServer/MCServer.dir/flags.make
src/CMakeFiles/../MCServer/MCServer.dir/Log.cpp.o: src/Log.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/tycho/MCServer/CMakeFiles $(CMAKE_PROGRESS_16)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object src/CMakeFiles/../MCServer/MCServer.dir/Log.cpp.o"
	cd /home/tycho/MCServer/src && /usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/../MCServer/MCServer.dir/Log.cpp.o -c /home/tycho/MCServer/src/Log.cpp

src/CMakeFiles/../MCServer/MCServer.dir/Log.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../MCServer/MCServer.dir/Log.cpp.i"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/tycho/MCServer/src/Log.cpp > CMakeFiles/../MCServer/MCServer.dir/Log.cpp.i

src/CMakeFiles/../MCServer/MCServer.dir/Log.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../MCServer/MCServer.dir/Log.cpp.s"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/tycho/MCServer/src/Log.cpp -o CMakeFiles/../MCServer/MCServer.dir/Log.cpp.s

src/CMakeFiles/../MCServer/MCServer.dir/Log.cpp.o.requires:
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/Log.cpp.o.requires

src/CMakeFiles/../MCServer/MCServer.dir/Log.cpp.o.provides: src/CMakeFiles/../MCServer/MCServer.dir/Log.cpp.o.requires
	$(MAKE) -f src/CMakeFiles/../MCServer/MCServer.dir/build.make src/CMakeFiles/../MCServer/MCServer.dir/Log.cpp.o.provides.build
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/Log.cpp.o.provides

src/CMakeFiles/../MCServer/MCServer.dir/Log.cpp.o.provides.build: src/CMakeFiles/../MCServer/MCServer.dir/Log.cpp.o

src/CMakeFiles/../MCServer/MCServer.dir/ClientHandle.cpp.o: src/CMakeFiles/../MCServer/MCServer.dir/flags.make
src/CMakeFiles/../MCServer/MCServer.dir/ClientHandle.cpp.o: src/ClientHandle.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/tycho/MCServer/CMakeFiles $(CMAKE_PROGRESS_17)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object src/CMakeFiles/../MCServer/MCServer.dir/ClientHandle.cpp.o"
	cd /home/tycho/MCServer/src && /usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/../MCServer/MCServer.dir/ClientHandle.cpp.o -c /home/tycho/MCServer/src/ClientHandle.cpp

src/CMakeFiles/../MCServer/MCServer.dir/ClientHandle.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../MCServer/MCServer.dir/ClientHandle.cpp.i"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/tycho/MCServer/src/ClientHandle.cpp > CMakeFiles/../MCServer/MCServer.dir/ClientHandle.cpp.i

src/CMakeFiles/../MCServer/MCServer.dir/ClientHandle.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../MCServer/MCServer.dir/ClientHandle.cpp.s"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/tycho/MCServer/src/ClientHandle.cpp -o CMakeFiles/../MCServer/MCServer.dir/ClientHandle.cpp.s

src/CMakeFiles/../MCServer/MCServer.dir/ClientHandle.cpp.o.requires:
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/ClientHandle.cpp.o.requires

src/CMakeFiles/../MCServer/MCServer.dir/ClientHandle.cpp.o.provides: src/CMakeFiles/../MCServer/MCServer.dir/ClientHandle.cpp.o.requires
	$(MAKE) -f src/CMakeFiles/../MCServer/MCServer.dir/build.make src/CMakeFiles/../MCServer/MCServer.dir/ClientHandle.cpp.o.provides.build
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/ClientHandle.cpp.o.provides

src/CMakeFiles/../MCServer/MCServer.dir/ClientHandle.cpp.o.provides.build: src/CMakeFiles/../MCServer/MCServer.dir/ClientHandle.cpp.o

src/CMakeFiles/../MCServer/MCServer.dir/ChatColor.cpp.o: src/CMakeFiles/../MCServer/MCServer.dir/flags.make
src/CMakeFiles/../MCServer/MCServer.dir/ChatColor.cpp.o: src/ChatColor.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/tycho/MCServer/CMakeFiles $(CMAKE_PROGRESS_18)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object src/CMakeFiles/../MCServer/MCServer.dir/ChatColor.cpp.o"
	cd /home/tycho/MCServer/src && /usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/../MCServer/MCServer.dir/ChatColor.cpp.o -c /home/tycho/MCServer/src/ChatColor.cpp

src/CMakeFiles/../MCServer/MCServer.dir/ChatColor.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../MCServer/MCServer.dir/ChatColor.cpp.i"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/tycho/MCServer/src/ChatColor.cpp > CMakeFiles/../MCServer/MCServer.dir/ChatColor.cpp.i

src/CMakeFiles/../MCServer/MCServer.dir/ChatColor.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../MCServer/MCServer.dir/ChatColor.cpp.s"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/tycho/MCServer/src/ChatColor.cpp -o CMakeFiles/../MCServer/MCServer.dir/ChatColor.cpp.s

src/CMakeFiles/../MCServer/MCServer.dir/ChatColor.cpp.o.requires:
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/ChatColor.cpp.o.requires

src/CMakeFiles/../MCServer/MCServer.dir/ChatColor.cpp.o.provides: src/CMakeFiles/../MCServer/MCServer.dir/ChatColor.cpp.o.requires
	$(MAKE) -f src/CMakeFiles/../MCServer/MCServer.dir/build.make src/CMakeFiles/../MCServer/MCServer.dir/ChatColor.cpp.o.provides.build
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/ChatColor.cpp.o.provides

src/CMakeFiles/../MCServer/MCServer.dir/ChatColor.cpp.o.provides.build: src/CMakeFiles/../MCServer/MCServer.dir/ChatColor.cpp.o

src/CMakeFiles/../MCServer/MCServer.dir/Group.cpp.o: src/CMakeFiles/../MCServer/MCServer.dir/flags.make
src/CMakeFiles/../MCServer/MCServer.dir/Group.cpp.o: src/Group.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/tycho/MCServer/CMakeFiles $(CMAKE_PROGRESS_19)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object src/CMakeFiles/../MCServer/MCServer.dir/Group.cpp.o"
	cd /home/tycho/MCServer/src && /usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/../MCServer/MCServer.dir/Group.cpp.o -c /home/tycho/MCServer/src/Group.cpp

src/CMakeFiles/../MCServer/MCServer.dir/Group.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../MCServer/MCServer.dir/Group.cpp.i"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/tycho/MCServer/src/Group.cpp > CMakeFiles/../MCServer/MCServer.dir/Group.cpp.i

src/CMakeFiles/../MCServer/MCServer.dir/Group.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../MCServer/MCServer.dir/Group.cpp.s"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/tycho/MCServer/src/Group.cpp -o CMakeFiles/../MCServer/MCServer.dir/Group.cpp.s

src/CMakeFiles/../MCServer/MCServer.dir/Group.cpp.o.requires:
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/Group.cpp.o.requires

src/CMakeFiles/../MCServer/MCServer.dir/Group.cpp.o.provides: src/CMakeFiles/../MCServer/MCServer.dir/Group.cpp.o.requires
	$(MAKE) -f src/CMakeFiles/../MCServer/MCServer.dir/build.make src/CMakeFiles/../MCServer/MCServer.dir/Group.cpp.o.provides.build
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/Group.cpp.o.provides

src/CMakeFiles/../MCServer/MCServer.dir/Group.cpp.o.provides.build: src/CMakeFiles/../MCServer/MCServer.dir/Group.cpp.o

src/CMakeFiles/../MCServer/MCServer.dir/Enchantments.cpp.o: src/CMakeFiles/../MCServer/MCServer.dir/flags.make
src/CMakeFiles/../MCServer/MCServer.dir/Enchantments.cpp.o: src/Enchantments.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/tycho/MCServer/CMakeFiles $(CMAKE_PROGRESS_20)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object src/CMakeFiles/../MCServer/MCServer.dir/Enchantments.cpp.o"
	cd /home/tycho/MCServer/src && /usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/../MCServer/MCServer.dir/Enchantments.cpp.o -c /home/tycho/MCServer/src/Enchantments.cpp

src/CMakeFiles/../MCServer/MCServer.dir/Enchantments.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../MCServer/MCServer.dir/Enchantments.cpp.i"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/tycho/MCServer/src/Enchantments.cpp > CMakeFiles/../MCServer/MCServer.dir/Enchantments.cpp.i

src/CMakeFiles/../MCServer/MCServer.dir/Enchantments.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../MCServer/MCServer.dir/Enchantments.cpp.s"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/tycho/MCServer/src/Enchantments.cpp -o CMakeFiles/../MCServer/MCServer.dir/Enchantments.cpp.s

src/CMakeFiles/../MCServer/MCServer.dir/Enchantments.cpp.o.requires:
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/Enchantments.cpp.o.requires

src/CMakeFiles/../MCServer/MCServer.dir/Enchantments.cpp.o.provides: src/CMakeFiles/../MCServer/MCServer.dir/Enchantments.cpp.o.requires
	$(MAKE) -f src/CMakeFiles/../MCServer/MCServer.dir/build.make src/CMakeFiles/../MCServer/MCServer.dir/Enchantments.cpp.o.provides.build
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/Enchantments.cpp.o.provides

src/CMakeFiles/../MCServer/MCServer.dir/Enchantments.cpp.o.provides.build: src/CMakeFiles/../MCServer/MCServer.dir/Enchantments.cpp.o

src/CMakeFiles/../MCServer/MCServer.dir/ChunkMap.cpp.o: src/CMakeFiles/../MCServer/MCServer.dir/flags.make
src/CMakeFiles/../MCServer/MCServer.dir/ChunkMap.cpp.o: src/ChunkMap.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/tycho/MCServer/CMakeFiles $(CMAKE_PROGRESS_21)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object src/CMakeFiles/../MCServer/MCServer.dir/ChunkMap.cpp.o"
	cd /home/tycho/MCServer/src && /usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/../MCServer/MCServer.dir/ChunkMap.cpp.o -c /home/tycho/MCServer/src/ChunkMap.cpp

src/CMakeFiles/../MCServer/MCServer.dir/ChunkMap.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../MCServer/MCServer.dir/ChunkMap.cpp.i"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/tycho/MCServer/src/ChunkMap.cpp > CMakeFiles/../MCServer/MCServer.dir/ChunkMap.cpp.i

src/CMakeFiles/../MCServer/MCServer.dir/ChunkMap.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../MCServer/MCServer.dir/ChunkMap.cpp.s"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/tycho/MCServer/src/ChunkMap.cpp -o CMakeFiles/../MCServer/MCServer.dir/ChunkMap.cpp.s

src/CMakeFiles/../MCServer/MCServer.dir/ChunkMap.cpp.o.requires:
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/ChunkMap.cpp.o.requires

src/CMakeFiles/../MCServer/MCServer.dir/ChunkMap.cpp.o.provides: src/CMakeFiles/../MCServer/MCServer.dir/ChunkMap.cpp.o.requires
	$(MAKE) -f src/CMakeFiles/../MCServer/MCServer.dir/build.make src/CMakeFiles/../MCServer/MCServer.dir/ChunkMap.cpp.o.provides.build
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/ChunkMap.cpp.o.provides

src/CMakeFiles/../MCServer/MCServer.dir/ChunkMap.cpp.o.provides.build: src/CMakeFiles/../MCServer/MCServer.dir/ChunkMap.cpp.o

src/CMakeFiles/../MCServer/MCServer.dir/ChunkSender.cpp.o: src/CMakeFiles/../MCServer/MCServer.dir/flags.make
src/CMakeFiles/../MCServer/MCServer.dir/ChunkSender.cpp.o: src/ChunkSender.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/tycho/MCServer/CMakeFiles $(CMAKE_PROGRESS_22)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object src/CMakeFiles/../MCServer/MCServer.dir/ChunkSender.cpp.o"
	cd /home/tycho/MCServer/src && /usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/../MCServer/MCServer.dir/ChunkSender.cpp.o -c /home/tycho/MCServer/src/ChunkSender.cpp

src/CMakeFiles/../MCServer/MCServer.dir/ChunkSender.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../MCServer/MCServer.dir/ChunkSender.cpp.i"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/tycho/MCServer/src/ChunkSender.cpp > CMakeFiles/../MCServer/MCServer.dir/ChunkSender.cpp.i

src/CMakeFiles/../MCServer/MCServer.dir/ChunkSender.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../MCServer/MCServer.dir/ChunkSender.cpp.s"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/tycho/MCServer/src/ChunkSender.cpp -o CMakeFiles/../MCServer/MCServer.dir/ChunkSender.cpp.s

src/CMakeFiles/../MCServer/MCServer.dir/ChunkSender.cpp.o.requires:
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/ChunkSender.cpp.o.requires

src/CMakeFiles/../MCServer/MCServer.dir/ChunkSender.cpp.o.provides: src/CMakeFiles/../MCServer/MCServer.dir/ChunkSender.cpp.o.requires
	$(MAKE) -f src/CMakeFiles/../MCServer/MCServer.dir/build.make src/CMakeFiles/../MCServer/MCServer.dir/ChunkSender.cpp.o.provides.build
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/ChunkSender.cpp.o.provides

src/CMakeFiles/../MCServer/MCServer.dir/ChunkSender.cpp.o.provides.build: src/CMakeFiles/../MCServer/MCServer.dir/ChunkSender.cpp.o

src/CMakeFiles/../MCServer/MCServer.dir/LightingThread.cpp.o: src/CMakeFiles/../MCServer/MCServer.dir/flags.make
src/CMakeFiles/../MCServer/MCServer.dir/LightingThread.cpp.o: src/LightingThread.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/tycho/MCServer/CMakeFiles $(CMAKE_PROGRESS_23)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object src/CMakeFiles/../MCServer/MCServer.dir/LightingThread.cpp.o"
	cd /home/tycho/MCServer/src && /usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/../MCServer/MCServer.dir/LightingThread.cpp.o -c /home/tycho/MCServer/src/LightingThread.cpp

src/CMakeFiles/../MCServer/MCServer.dir/LightingThread.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../MCServer/MCServer.dir/LightingThread.cpp.i"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/tycho/MCServer/src/LightingThread.cpp > CMakeFiles/../MCServer/MCServer.dir/LightingThread.cpp.i

src/CMakeFiles/../MCServer/MCServer.dir/LightingThread.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../MCServer/MCServer.dir/LightingThread.cpp.s"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/tycho/MCServer/src/LightingThread.cpp -o CMakeFiles/../MCServer/MCServer.dir/LightingThread.cpp.s

src/CMakeFiles/../MCServer/MCServer.dir/LightingThread.cpp.o.requires:
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/LightingThread.cpp.o.requires

src/CMakeFiles/../MCServer/MCServer.dir/LightingThread.cpp.o.provides: src/CMakeFiles/../MCServer/MCServer.dir/LightingThread.cpp.o.requires
	$(MAKE) -f src/CMakeFiles/../MCServer/MCServer.dir/build.make src/CMakeFiles/../MCServer/MCServer.dir/LightingThread.cpp.o.provides.build
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/LightingThread.cpp.o.provides

src/CMakeFiles/../MCServer/MCServer.dir/LightingThread.cpp.o.provides.build: src/CMakeFiles/../MCServer/MCServer.dir/LightingThread.cpp.o

src/CMakeFiles/../MCServer/MCServer.dir/MobCensus.cpp.o: src/CMakeFiles/../MCServer/MCServer.dir/flags.make
src/CMakeFiles/../MCServer/MCServer.dir/MobCensus.cpp.o: src/MobCensus.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/tycho/MCServer/CMakeFiles $(CMAKE_PROGRESS_24)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object src/CMakeFiles/../MCServer/MCServer.dir/MobCensus.cpp.o"
	cd /home/tycho/MCServer/src && /usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/../MCServer/MCServer.dir/MobCensus.cpp.o -c /home/tycho/MCServer/src/MobCensus.cpp

src/CMakeFiles/../MCServer/MCServer.dir/MobCensus.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../MCServer/MCServer.dir/MobCensus.cpp.i"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/tycho/MCServer/src/MobCensus.cpp > CMakeFiles/../MCServer/MCServer.dir/MobCensus.cpp.i

src/CMakeFiles/../MCServer/MCServer.dir/MobCensus.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../MCServer/MCServer.dir/MobCensus.cpp.s"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/tycho/MCServer/src/MobCensus.cpp -o CMakeFiles/../MCServer/MCServer.dir/MobCensus.cpp.s

src/CMakeFiles/../MCServer/MCServer.dir/MobCensus.cpp.o.requires:
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/MobCensus.cpp.o.requires

src/CMakeFiles/../MCServer/MCServer.dir/MobCensus.cpp.o.provides: src/CMakeFiles/../MCServer/MCServer.dir/MobCensus.cpp.o.requires
	$(MAKE) -f src/CMakeFiles/../MCServer/MCServer.dir/build.make src/CMakeFiles/../MCServer/MCServer.dir/MobCensus.cpp.o.provides.build
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/MobCensus.cpp.o.provides

src/CMakeFiles/../MCServer/MCServer.dir/MobCensus.cpp.o.provides.build: src/CMakeFiles/../MCServer/MCServer.dir/MobCensus.cpp.o

src/CMakeFiles/../MCServer/MCServer.dir/MobSpawner.cpp.o: src/CMakeFiles/../MCServer/MCServer.dir/flags.make
src/CMakeFiles/../MCServer/MCServer.dir/MobSpawner.cpp.o: src/MobSpawner.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/tycho/MCServer/CMakeFiles $(CMAKE_PROGRESS_25)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object src/CMakeFiles/../MCServer/MCServer.dir/MobSpawner.cpp.o"
	cd /home/tycho/MCServer/src && /usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/../MCServer/MCServer.dir/MobSpawner.cpp.o -c /home/tycho/MCServer/src/MobSpawner.cpp

src/CMakeFiles/../MCServer/MCServer.dir/MobSpawner.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../MCServer/MCServer.dir/MobSpawner.cpp.i"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/tycho/MCServer/src/MobSpawner.cpp > CMakeFiles/../MCServer/MCServer.dir/MobSpawner.cpp.i

src/CMakeFiles/../MCServer/MCServer.dir/MobSpawner.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../MCServer/MCServer.dir/MobSpawner.cpp.s"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/tycho/MCServer/src/MobSpawner.cpp -o CMakeFiles/../MCServer/MCServer.dir/MobSpawner.cpp.s

src/CMakeFiles/../MCServer/MCServer.dir/MobSpawner.cpp.o.requires:
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/MobSpawner.cpp.o.requires

src/CMakeFiles/../MCServer/MCServer.dir/MobSpawner.cpp.o.provides: src/CMakeFiles/../MCServer/MCServer.dir/MobSpawner.cpp.o.requires
	$(MAKE) -f src/CMakeFiles/../MCServer/MCServer.dir/build.make src/CMakeFiles/../MCServer/MCServer.dir/MobSpawner.cpp.o.provides.build
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/MobSpawner.cpp.o.provides

src/CMakeFiles/../MCServer/MCServer.dir/MobSpawner.cpp.o.provides.build: src/CMakeFiles/../MCServer/MCServer.dir/MobSpawner.cpp.o

src/CMakeFiles/../MCServer/MCServer.dir/MobProximityCounter.cpp.o: src/CMakeFiles/../MCServer/MCServer.dir/flags.make
src/CMakeFiles/../MCServer/MCServer.dir/MobProximityCounter.cpp.o: src/MobProximityCounter.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/tycho/MCServer/CMakeFiles $(CMAKE_PROGRESS_26)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object src/CMakeFiles/../MCServer/MCServer.dir/MobProximityCounter.cpp.o"
	cd /home/tycho/MCServer/src && /usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/../MCServer/MCServer.dir/MobProximityCounter.cpp.o -c /home/tycho/MCServer/src/MobProximityCounter.cpp

src/CMakeFiles/../MCServer/MCServer.dir/MobProximityCounter.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../MCServer/MCServer.dir/MobProximityCounter.cpp.i"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/tycho/MCServer/src/MobProximityCounter.cpp > CMakeFiles/../MCServer/MCServer.dir/MobProximityCounter.cpp.i

src/CMakeFiles/../MCServer/MCServer.dir/MobProximityCounter.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../MCServer/MCServer.dir/MobProximityCounter.cpp.s"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/tycho/MCServer/src/MobProximityCounter.cpp -o CMakeFiles/../MCServer/MCServer.dir/MobProximityCounter.cpp.s

src/CMakeFiles/../MCServer/MCServer.dir/MobProximityCounter.cpp.o.requires:
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/MobProximityCounter.cpp.o.requires

src/CMakeFiles/../MCServer/MCServer.dir/MobProximityCounter.cpp.o.provides: src/CMakeFiles/../MCServer/MCServer.dir/MobProximityCounter.cpp.o.requires
	$(MAKE) -f src/CMakeFiles/../MCServer/MCServer.dir/build.make src/CMakeFiles/../MCServer/MCServer.dir/MobProximityCounter.cpp.o.provides.build
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/MobProximityCounter.cpp.o.provides

src/CMakeFiles/../MCServer/MCServer.dir/MobProximityCounter.cpp.o.provides.build: src/CMakeFiles/../MCServer/MCServer.dir/MobProximityCounter.cpp.o

src/CMakeFiles/../MCServer/MCServer.dir/Noise.cpp.o: src/CMakeFiles/../MCServer/MCServer.dir/flags.make
src/CMakeFiles/../MCServer/MCServer.dir/Noise.cpp.o: src/Noise.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/tycho/MCServer/CMakeFiles $(CMAKE_PROGRESS_27)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object src/CMakeFiles/../MCServer/MCServer.dir/Noise.cpp.o"
	cd /home/tycho/MCServer/src && /usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/../MCServer/MCServer.dir/Noise.cpp.o -c /home/tycho/MCServer/src/Noise.cpp

src/CMakeFiles/../MCServer/MCServer.dir/Noise.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../MCServer/MCServer.dir/Noise.cpp.i"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/tycho/MCServer/src/Noise.cpp > CMakeFiles/../MCServer/MCServer.dir/Noise.cpp.i

src/CMakeFiles/../MCServer/MCServer.dir/Noise.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../MCServer/MCServer.dir/Noise.cpp.s"
	cd /home/tycho/MCServer/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/tycho/MCServer/src/Noise.cpp -o CMakeFiles/../MCServer/MCServer.dir/Noise.cpp.s

src/CMakeFiles/../MCServer/MCServer.dir/Noise.cpp.o.requires:
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/Noise.cpp.o.requires

src/CMakeFiles/../MCServer/MCServer.dir/Noise.cpp.o.provides: src/CMakeFiles/../MCServer/MCServer.dir/Noise.cpp.o.requires
	$(MAKE) -f src/CMakeFiles/../MCServer/MCServer.dir/build.make src/CMakeFiles/../MCServer/MCServer.dir/Noise.cpp.o.provides.build
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/Noise.cpp.o.provides

src/CMakeFiles/../MCServer/MCServer.dir/Noise.cpp.o.provides.build: src/CMakeFiles/../MCServer/MCServer.dir/Noise.cpp.o

# Object files for target ../MCServer/MCServer
__/MCServer/MCServer_OBJECTS = \
"CMakeFiles/../MCServer/MCServer.dir/main.cpp.o" \
"CMakeFiles/../MCServer/MCServer.dir/Root.cpp.o" \
"CMakeFiles/../MCServer/MCServer.dir/MCLogger.cpp.o" \
"CMakeFiles/../MCServer/MCServer.dir/Authenticator.cpp.o" \
"CMakeFiles/../MCServer/MCServer.dir/StringUtils.cpp.o" \
"CMakeFiles/../MCServer/MCServer.dir/Server.cpp.o" \
"CMakeFiles/../MCServer/MCServer.dir/DeadlockDetect.cpp.o" \
"CMakeFiles/../MCServer/MCServer.dir/WebAdmin.cpp.o" \
"CMakeFiles/../MCServer/MCServer.dir/GroupManager.cpp.o" \
"CMakeFiles/../MCServer/MCServer.dir/CraftingRecipes.cpp.o" \
"CMakeFiles/../MCServer/MCServer.dir/FurnaceRecipe.cpp.o" \
"CMakeFiles/../MCServer/MCServer.dir/MonsterConfig.cpp.o" \
"CMakeFiles/../MCServer/MCServer.dir/World.cpp.o" \
"CMakeFiles/../MCServer/MCServer.dir/CommandOutput.cpp.o" \
"CMakeFiles/../MCServer/MCServer.dir/RCONServer.cpp.o" \
"CMakeFiles/../MCServer/MCServer.dir/Log.cpp.o" \
"CMakeFiles/../MCServer/MCServer.dir/ClientHandle.cpp.o" \
"CMakeFiles/../MCServer/MCServer.dir/ChatColor.cpp.o" \
"CMakeFiles/../MCServer/MCServer.dir/Group.cpp.o" \
"CMakeFiles/../MCServer/MCServer.dir/Enchantments.cpp.o" \
"CMakeFiles/../MCServer/MCServer.dir/ChunkMap.cpp.o" \
"CMakeFiles/../MCServer/MCServer.dir/ChunkSender.cpp.o" \
"CMakeFiles/../MCServer/MCServer.dir/LightingThread.cpp.o" \
"CMakeFiles/../MCServer/MCServer.dir/MobCensus.cpp.o" \
"CMakeFiles/../MCServer/MCServer.dir/MobSpawner.cpp.o" \
"CMakeFiles/../MCServer/MCServer.dir/MobProximityCounter.cpp.o" \
"CMakeFiles/../MCServer/MCServer.dir/Noise.cpp.o"

# External object files for target ../MCServer/MCServer
__/MCServer/MCServer_EXTERNAL_OBJECTS =

src/../MCServer/MCServer: src/CMakeFiles/../MCServer/MCServer.dir/main.cpp.o
src/../MCServer/MCServer: src/CMakeFiles/../MCServer/MCServer.dir/Root.cpp.o
src/../MCServer/MCServer: src/CMakeFiles/../MCServer/MCServer.dir/MCLogger.cpp.o
src/../MCServer/MCServer: src/CMakeFiles/../MCServer/MCServer.dir/Authenticator.cpp.o
src/../MCServer/MCServer: src/CMakeFiles/../MCServer/MCServer.dir/StringUtils.cpp.o
src/../MCServer/MCServer: src/CMakeFiles/../MCServer/MCServer.dir/Server.cpp.o
src/../MCServer/MCServer: src/CMakeFiles/../MCServer/MCServer.dir/DeadlockDetect.cpp.o
src/../MCServer/MCServer: src/CMakeFiles/../MCServer/MCServer.dir/WebAdmin.cpp.o
src/../MCServer/MCServer: src/CMakeFiles/../MCServer/MCServer.dir/GroupManager.cpp.o
src/../MCServer/MCServer: src/CMakeFiles/../MCServer/MCServer.dir/CraftingRecipes.cpp.o
src/../MCServer/MCServer: src/CMakeFiles/../MCServer/MCServer.dir/FurnaceRecipe.cpp.o
src/../MCServer/MCServer: src/CMakeFiles/../MCServer/MCServer.dir/MonsterConfig.cpp.o
src/../MCServer/MCServer: src/CMakeFiles/../MCServer/MCServer.dir/World.cpp.o
src/../MCServer/MCServer: src/CMakeFiles/../MCServer/MCServer.dir/CommandOutput.cpp.o
src/../MCServer/MCServer: src/CMakeFiles/../MCServer/MCServer.dir/RCONServer.cpp.o
src/../MCServer/MCServer: src/CMakeFiles/../MCServer/MCServer.dir/Log.cpp.o
src/../MCServer/MCServer: src/CMakeFiles/../MCServer/MCServer.dir/ClientHandle.cpp.o
src/../MCServer/MCServer: src/CMakeFiles/../MCServer/MCServer.dir/ChatColor.cpp.o
src/../MCServer/MCServer: src/CMakeFiles/../MCServer/MCServer.dir/Group.cpp.o
src/../MCServer/MCServer: src/CMakeFiles/../MCServer/MCServer.dir/Enchantments.cpp.o
src/../MCServer/MCServer: src/CMakeFiles/../MCServer/MCServer.dir/ChunkMap.cpp.o
src/../MCServer/MCServer: src/CMakeFiles/../MCServer/MCServer.dir/ChunkSender.cpp.o
src/../MCServer/MCServer: src/CMakeFiles/../MCServer/MCServer.dir/LightingThread.cpp.o
src/../MCServer/MCServer: src/CMakeFiles/../MCServer/MCServer.dir/MobCensus.cpp.o
src/../MCServer/MCServer: src/CMakeFiles/../MCServer/MCServer.dir/MobSpawner.cpp.o
src/../MCServer/MCServer: src/CMakeFiles/../MCServer/MCServer.dir/MobProximityCounter.cpp.o
src/../MCServer/MCServer: src/CMakeFiles/../MCServer/MCServer.dir/Noise.cpp.o
src/../MCServer/MCServer: src/OSSupport/libOSSupport.a
src/../MCServer/MCServer: src/HTTPServer/libHTTPServer.a
src/../MCServer/MCServer: lib/inifile/libiniFile.a
src/../MCServer/MCServer: src/Bindings/libBindings.a
src/../MCServer/MCServer: src/Items/libItems.a
src/../MCServer/MCServer: src/Blocks/libBlocks.a
src/../MCServer/MCServer: src/Protocol/libProtocol.a
src/../MCServer/MCServer: src/Generating/libGenerating.a
src/../MCServer/MCServer: src/WorldStorage/libWorldStorage.a
src/../MCServer/MCServer: lib/jsoncpp/libjsoncpp.a
src/../MCServer/MCServer: lib/cryptopp/libcryptopp.a
src/../MCServer/MCServer: src/Mobs/libMobs.a
src/../MCServer/MCServer: src/Entities/libEntities.a
src/../MCServer/MCServer: src/Simulator/libSimulator.a
src/../MCServer/MCServer: src/CMakeFiles/../MCServer/MCServer.dir/build.make
src/../MCServer/MCServer: src/CMakeFiles/../MCServer/MCServer.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --red --bold "Linking CXX executable ../MCServer/MCServer"
	cd /home/tycho/MCServer/src && $(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/../MCServer/MCServer.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
src/CMakeFiles/../MCServer/MCServer.dir/build: src/../MCServer/MCServer
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/build

src/CMakeFiles/../MCServer/MCServer.dir/requires: src/CMakeFiles/../MCServer/MCServer.dir/main.cpp.o.requires
src/CMakeFiles/../MCServer/MCServer.dir/requires: src/CMakeFiles/../MCServer/MCServer.dir/Root.cpp.o.requires
src/CMakeFiles/../MCServer/MCServer.dir/requires: src/CMakeFiles/../MCServer/MCServer.dir/MCLogger.cpp.o.requires
src/CMakeFiles/../MCServer/MCServer.dir/requires: src/CMakeFiles/../MCServer/MCServer.dir/Authenticator.cpp.o.requires
src/CMakeFiles/../MCServer/MCServer.dir/requires: src/CMakeFiles/../MCServer/MCServer.dir/StringUtils.cpp.o.requires
src/CMakeFiles/../MCServer/MCServer.dir/requires: src/CMakeFiles/../MCServer/MCServer.dir/Server.cpp.o.requires
src/CMakeFiles/../MCServer/MCServer.dir/requires: src/CMakeFiles/../MCServer/MCServer.dir/DeadlockDetect.cpp.o.requires
src/CMakeFiles/../MCServer/MCServer.dir/requires: src/CMakeFiles/../MCServer/MCServer.dir/WebAdmin.cpp.o.requires
src/CMakeFiles/../MCServer/MCServer.dir/requires: src/CMakeFiles/../MCServer/MCServer.dir/GroupManager.cpp.o.requires
src/CMakeFiles/../MCServer/MCServer.dir/requires: src/CMakeFiles/../MCServer/MCServer.dir/CraftingRecipes.cpp.o.requires
src/CMakeFiles/../MCServer/MCServer.dir/requires: src/CMakeFiles/../MCServer/MCServer.dir/FurnaceRecipe.cpp.o.requires
src/CMakeFiles/../MCServer/MCServer.dir/requires: src/CMakeFiles/../MCServer/MCServer.dir/MonsterConfig.cpp.o.requires
src/CMakeFiles/../MCServer/MCServer.dir/requires: src/CMakeFiles/../MCServer/MCServer.dir/World.cpp.o.requires
src/CMakeFiles/../MCServer/MCServer.dir/requires: src/CMakeFiles/../MCServer/MCServer.dir/CommandOutput.cpp.o.requires
src/CMakeFiles/../MCServer/MCServer.dir/requires: src/CMakeFiles/../MCServer/MCServer.dir/RCONServer.cpp.o.requires
src/CMakeFiles/../MCServer/MCServer.dir/requires: src/CMakeFiles/../MCServer/MCServer.dir/Log.cpp.o.requires
src/CMakeFiles/../MCServer/MCServer.dir/requires: src/CMakeFiles/../MCServer/MCServer.dir/ClientHandle.cpp.o.requires
src/CMakeFiles/../MCServer/MCServer.dir/requires: src/CMakeFiles/../MCServer/MCServer.dir/ChatColor.cpp.o.requires
src/CMakeFiles/../MCServer/MCServer.dir/requires: src/CMakeFiles/../MCServer/MCServer.dir/Group.cpp.o.requires
src/CMakeFiles/../MCServer/MCServer.dir/requires: src/CMakeFiles/../MCServer/MCServer.dir/Enchantments.cpp.o.requires
src/CMakeFiles/../MCServer/MCServer.dir/requires: src/CMakeFiles/../MCServer/MCServer.dir/ChunkMap.cpp.o.requires
src/CMakeFiles/../MCServer/MCServer.dir/requires: src/CMakeFiles/../MCServer/MCServer.dir/ChunkSender.cpp.o.requires
src/CMakeFiles/../MCServer/MCServer.dir/requires: src/CMakeFiles/../MCServer/MCServer.dir/LightingThread.cpp.o.requires
src/CMakeFiles/../MCServer/MCServer.dir/requires: src/CMakeFiles/../MCServer/MCServer.dir/MobCensus.cpp.o.requires
src/CMakeFiles/../MCServer/MCServer.dir/requires: src/CMakeFiles/../MCServer/MCServer.dir/MobSpawner.cpp.o.requires
src/CMakeFiles/../MCServer/MCServer.dir/requires: src/CMakeFiles/../MCServer/MCServer.dir/MobProximityCounter.cpp.o.requires
src/CMakeFiles/../MCServer/MCServer.dir/requires: src/CMakeFiles/../MCServer/MCServer.dir/Noise.cpp.o.requires
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/requires

src/CMakeFiles/../MCServer/MCServer.dir/clean:
	cd /home/tycho/MCServer/src && $(CMAKE_COMMAND) -P CMakeFiles/../MCServer/MCServer.dir/cmake_clean.cmake
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/clean

src/CMakeFiles/../MCServer/MCServer.dir/depend:
	cd /home/tycho/MCServer && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /home/tycho/MCServer /home/tycho/MCServer/src /home/tycho/MCServer /home/tycho/MCServer/src /home/tycho/MCServer/src/MCServer/MCServer.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : src/CMakeFiles/../MCServer/MCServer.dir/depend

