# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# compile CXX with /usr/bin/c++
CXX_FLAGS =  -std=c++03 -isystem /home/tycho/MCServer/src/../lib -isystem /home/tycho/MCServer/src/../lib/jsoncpp/include   

CXX_DEFINES = 

