#pragma once

enum ENUM_BIOME_ID
{
  E_BIOME_OCEAN = 0,
  E_BIOME_PLAINS = 1,
  E_BIOME_DESERT = 2,
  E_BIOME_EXTREME_HILLS = 3,
  E_BIOME_FOREST = 4,
  E_BIOME_TAIGA = 5,
  E_BIOME_SWAMPLAND = 6,
  E_BIOME_RIVER = 7,
  E_BIOME_HELL = 8,
  E_BIOME_SKY = 9,
  E_BIOME_FROZEN_OCEAN = 10,
  E_BIOME_FROZEN_RIVER = 11,
  E_BIOME_ICE_PLAINS = 12,
  E_BIOME_ICE_MOUNTAINS = 13,
  E_BIOME_MUSHROOM_ISLAND = 14,
  E_BIOME_MUSHROOM_ISLAND_SHORE = 15,
  E_BIOME_BEACH = 16,
  E_BIOME_DESERT_HILLS = 17,
  E_BIOME_FOREST_HILLS = 18,
  E_BIOME_TAIGA_HILLS = 19,
  E_BIOME_EXTREME_HILLS_EDGE = 20,
  E_BIOME_JUNGLE = 21,
  E_BIOME_JUNGLE_HILLS = 22,
  E_BIOME_JUNGLE_EDGE = 23,
  E_BIOME_DEEP_OCEAN = 24,
  E_BIOME_STONE_BEACH = 25,
  E_BIOME_COLD_BEACH = 26,
  E_BIOME_BIRCH_FOREST = 27,
  E_BIOME_BIRCH_FOREST_HILL = 28,
  E_BIOME_ROOFED_FOREST = 29,
  E_BIOME_COLD_TAIGA = 30,
  E_BIOME_COLD_TAIGA_HILLS = 31,
  E_BIOME_MEGA_TAIGA = 32,
  E_BIOME_MEGA_TAIGA_HILLS = 33,
  E_BIOME_EXTREME_HILLS_PLUS = 34,
  E_BIOME_SAVANNA = 35,
  E_BIOME_SAVANNA_PLATEAU = 36,
  E_BIOME_MESA = 37,
  E_BIOME_MESA_PLATEAU_F = 38,
  E_BIOME_MESA_PLATEAU = 39,
  E_BIOME_SUNFLOWER_PLAINS = 129,
  E_BIOME_DESERT_M = 130,
  E_BIOME_EXTREME_HILLS_M = 131
  E_BIOME_FLOWER_FOREST = 132,
  E_BIOME_TAIGA_M = 133,
  E_BIOME_SWAMPLAND_M = 134,
  E_BIOME_ICE_PLAINS_SPIKES = 140,
  E_BIOME_JUNGLE_M = 149,
  E_BIOME_JUNGLE_EDGE_M = 151,
  E_BIOME_BIRCH_FOREST_M = 155,
  E_BIOME_BIRCH_FOREST_HILLS_M = 156,
  E_BIOME_ROOFED_FOREST_M = 157,
  E_BIOME_COLD_TAIGA_M = 158,
  E_BIOME_MEGA_SPRUCE_TAIGA = 160,
  E_BIOME_MEGA_SPRUCE_TAIGA_HILS = 161,
  E_BIOME_EXTREME_HILLS_PLUS_M = 162,
  E_BIOME_SAVANNA_M = 163,
  E_BIOME_SAVANNA_PLATEAU_M = 164,
  E_BIOME_MESA_BRYCE = 165,
  E_BIOME_MESA_PLATEAU_F_M = 166,
  E_BIOME_MESA_PLATEAU_M = 167,
};

enum ENUM_BIOME_TYPE_DEF
{
  E_BIOME_SNOW_COVERED = 0, // Temperature =< 0.15
  E_BIOME_COLD = 1,         // Temperature = {0.2, 0.25, 0.3}
  E_BIOME_MEDIUM = 2,       // Temperature = {0.5, 0.6, 0.7, 0.8, 0.95}
  E_BIOME_WARM = 3,         // Temperature => 1.0
  E_BIOME_NEUTRAL = 4,
};

