name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: glibc
      run: ldd --version

    - name: date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - name: builddir
      run: mkdir Release
      
    - name: cmake
      run: cmake .. -DNO_NATIVE_OPTIMIZATION=1 -DCMAKE_BUILD_TYPE=RELEASE
      working-directory: Release

    - name: make
      run: make -j`nproc`
      working-directory: Release
      env: 
        CUBERITE_BUILD_SERIES_NAME: Linux
        CUBERITE_BUILD_ID: ${{ github.run_number }}
        CUBERITE_BUILD_DATETIME: ${{ steps.date.outputs.date }}

    - run: echo Cuberite $CUBERITE_BUILD_SERIES_NAME-$CUBERITE_BUILD_ID > buildinfo.txt
      working-directory: Release/Server
      env: 
        CUBERITE_BUILD_SERIES_NAME: Linux
        CUBERITE_BUILD_ID: ${{ github.run_number }}
        CUBERITE_BUILD_DATETIME: ${{ steps.date.outputs.date }}

    - name: cleanup
      run: chmod 777 -R ./ && tar -hzcv -T ${{ github.workspace }}/Server/Install/UnixExecutables.list -f Cuberite.tar.gz
      working-directory: Release/Server

    - uses: actions/upload-artifact@v2
      with:
        name: Cuberite
        path: Release/Server/Cuberite.tar.gz
